#!/bin/bash
clear
# export QUICK_CHECK=x
set -e
uv --preview-features format format -- --line-length 120
uv run ssort --check --diff
set +e
ruff check .
uv run mypy .
if false; then
    if true; then
        uv run pytest -vv  # --capture=tee-sys --durations=5
    else
        uv run python -m cProfile -o out.prof .venv/bin/pytest -vv
        uv run snakeviz out.prof # --server
    fi
fi
