[project]
name = "tinyrenderer"
version = "0.0.1"
description = "Python port of https://haqr.eu/tinyrenderer/"
readme = "../README.md"
requires-python = ">=3.12"
dependencies = [
    "friendly>=0.7.21",
    "numpy>=2.5.1",
]

[dependency-groups]
dev = [
    "hypothesis>=6.164.0",
    "icecream>=2.2.0",
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
    "snakeviz>=2.2.2",
    "ssort>=0.17.0",
]

[tool.ruff]
line-length = 120
# output-prefer-rule-codes = true

[tool.ruff.format]
preview = true

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    "RUF",
]
ignore = ["UP040"]
preview = true

# [tool.mypy]
# plugins = ["numpy.typing.mypy_plugin", ]
