#!/bin/bash
if [[ ! -e ../.git/config ]]; then
  echo "Run only from python subdir!"
  exit
fi
read -r -d '' FILE_LIST << 'END'
../README.md
.gitignore
check
make_doc
pyproject.toml
uv.lock
lib/trtypes.py
lib/tgaimage.py
lib/__init__.py
lib/tests/test_trtypes.py
lib/tests/test_tgaimage.py
lib/tests/__init__.py
END
set -x
for f in ${FILE_LIST}; do
  git checkout python $f
done
